### ISSUE TITLE
Freezing on Window Resize/Maximize

### ISSUE THREAD

**Issue by bartoleo** [coliff/bootstrap-ie11#273]
### Prerequisites

- [X] I have [searched](https://github.com/coliff/bootstrap-ie11/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have validated any HTML to avoid common problems

### Describe the issue

I am having a problem when the user resizes or maximizes the window, IE freezes for several seconds.
The same thing happens to me also in the test page: https://coliff.github.io/bootstrap-ie11/tests/

### What version of Bootstrap are you using?

v5.3.2

**Comment by coliff** [comment]
I can reproduce this issue which I think is an unfortunate side effect from using the ie11CustomProperties polyfill.

You could consider not using that polyfill and instead using standard CSS for Internet Explorer. For example set:

```
body {
  font-family: system-ui, -apple-system, "Segoe UI", Roboto, "Helvetica Neue", "Noto Sans", "Liberation Sans", Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji";
  font-size: 1rem;
  font-weight: 400;
  line-height: 1.5;
  color: #212529;
  text-align: undefined;
  background-color: #fff;
}
```

so that the polyfill doesn't need to calculate everything from:

```css
body {
  font-family: var(--bs-body-font-family);
  font-size: var(--bs-body-font-size);
  font-weight: var(--bs-body-font-weight);
  line-height: var(--bs-body-line-height);
  color: var(--bs-body-color);
  text-align: var(--bs-body-text-align);
  background-color: var(--bs-body-bg);
}
```

You could try using: https://css-variables.github.io/ to help you achieve this. Paste in the CSS from: https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.css and copy across what you need.
