### ISSUE TITLE
Flexbox Gap Polyfill

### ISSUE THREAD

**Issue by coliff** [coliff/bootstrap-ie11#80]
The `.gap` CSS classes don't work in IE11 due to lack of support for Flexbox gap, but it can be polyfilled with CSS with something like:

```css
.gap-3 > * {
  margin-bottom: 1rem;
}

.gap-3 > *:last-child {
  margin-bottom: 0;
}
```
