### ISSUE TITLE
Vertical rule styling

### ISSUE THREAD

**Issue by coliff** [coliff/bootstrap-ie11#81]
Need to add CSS for it to display... something like:

```css
  .vr {
    border-right: 1px solid rgb(33, 37, 41);
  }
```
