### ISSUE TITLE
Fix for `.justify-content-evenly` flex utility

### ISSUE THREAD

**Issue by coliff** [coliff/bootstrap-ie11#84]
This doesn't work in IE11

```css
.justify-content-evenly {
  justify-content: space-evenly !important;
}
```

![image](https://user-images.githubusercontent.com/1212885/128817275-dc49ee10-7651-437d-bdab-aa6b54fef409.png)

should be fixed with a similar flex property such as:

```css
.justify-content-evenly {
  justify-content: space-around !important;
}
```
Then it'll appear like this:

![image](https://user-images.githubusercontent.com/1212885/128817205-982cf9e2-cc05-4983-8e59-219c68333171.png)
